name: thinkforliving
on:
  push:
    branches:
      - master
jobs:
  build:
    name: Build thinkforliving Web
    env:
      my_secret: ${{secrets.commit_secret}}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: subosito/flutter-action@v1
        with:
          channel: 'dev'
      - run: flutter config --enable-web
      - run: flutter pub get
      - run: flutter build web --release
      - run: |
          cd build/web
          git init
          # type configurations: your user.email and user.name followed lines 
          git config --global user.email shardul.srivastava007@gmail.com
          git config --global user.name "Shardul Srivastava"
          git config --global user.email onatcipli@outlook.com
          git config --global user.name onatcipli
          git status
          # change this remote url for examle your remote url is https://github.com/onatcipli/flutter_web.git then the following:
          git remote add origin https://${{secrets.commit_secret}}@github.com/thinkforliving/thinkforliving.github.io.git
          git checkout master
          git add --all
          git commit -m "add the build code"
          git push origin master -f